openapi: 3.0.0
components:
  schemas:
    CreateCharacterDocumentResponse:
      properties:
        code:
          type: number
        message:
          type: string
        data:
          type: object
          properties:
            id:
              type: string
            nombre:
              type: string
            altura:
              type: string
            masa:
              type: string
            color_cabello:
              type: string
            color_piel:
              type: string
            color_ojos:
              type: string
            nacimiento:
              type: string
            genero:
              type: string
            mundo_natal:
              type: string
            peliculas:
              type: array
              items:
                type: string
            especies:
              type: array
              items:
                type: string
            vehiculos:
              type: array
              items:
                type: string
            naves_estelares:
              type: array
              items:
                type: string
            created:
              type: string
            edited:
              type: string
            url:
              type: string
    CreateCharacterDocumentRequest:
      properties:
            nombre:
              type: string
            altura:
              type: string
            masa:
              type: string
            color_cabello:
              type: string
            color_piel:
              type: string
            color_ojos:
              type: string
            nacimiento:
              type: string
            genero:
              type: string
            mundo_natal:
              type: string
            peliculas:
              type: array
              items:
                type: string
            especies:
              type: array
              items:
                type: string
            vehiculos:
              type: array
              items:
                type: string
            naves_estelares:
              type: array
              items:
                type: string
            url:
              type: string
    ListCharactersDocumentResponse:
      properties:
        code:
          type: number
        message:
          type: string
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              nombre:
                type: string
              altura:
                type: string
              masa:
                type: string
              color_cabello:
                type: string
              color_piel:
                type: string
              color_ojos:
                type: string
              nacimiento:
                type: string
              genero:
                type: string
              mundo_natal:
                type: string
              peliculas:
                type: array
                items:
                  type: string
              especies:
                type: array
                items:
                  type: string
              vehiculos:
                type: array
                items:
                  type: string
              naves_estelares:
                type: array
                items:
                  type: string
              created:
                type: string
              edited:
                type: string
              url:
                type: string
  securitySchemes: {}
info:
  title: SWAPI Challenge - Jorge Rubina
  description: ''
  version: '1'
paths:
  /createCharacter:
    post:
      operationId: createCharacter
      description: Crea el personaje a traves del modelo definido
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCharacterDocumentRequest'
      responses:
        '200':
          description: Objeto de respuesta del personaje creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCharacterDocumentResponse'
  '/getCharacter/{id}':
    get:
      operationId: getCharacter
      description: Obtiene el personaje a traves del id
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Objeto de respuesta del personaje obtenido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCharacterDocumentResponse'
  /getAllCharacters:
    get:
      operationId: getAllCharacters
      description: Obtiene la lista de personajes creados
      responses:
        '200':
          description: Lista de personajes creados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListCharactersDocumentResponse'
  '/getSwapiCharacter/{id}':
    get:
      operationId: getSwapiCharacter
      description: Obtiene el personaje a traves del id de SWAPI
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Objeto de respuesta del personaje obtenido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCharacterDocumentResponse'
